server:
  port: ${server-port:9000}

jwt:
  sign-key: sky-spring-cloud

spring:
  application:
    name: authorization-center
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: "http://${ip:192.168.31.46}:8010/eureka"